//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.Core.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person : IEntity
    {
        public long IdPerson { get; set; }
        public string Name { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string StreetHome { get; set; }
        public string CityHome { get; set; }
        public string StateHome { get; set; }
        public Nullable<int> ZipHome { get; set; }
        public string StreetOffice { get; set; }
        public string CityOffice { get; set; }
        public string StateOffice { get; set; }
        public Nullable<int> ZipOffice { get; set; }
        public string FavoriteColors { get; set; }
        public string Discount { get; set; }
        public Nullable<long> Age { get; set; }
        public System.DateTime RecordTime { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
